annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: updated docs
apiVersion: v2
appVersion: "5.8"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.1
description: language-tool helm package
home: https://github.com/k8s-at-home/charts/tree/master/charts/incubator/language-tool
icon: https://languagetool.org/images/logo_color_with_background.svg?8dae54218b449e94603195c91016bc93
keywords:
  - language-tool
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: zekker6
    email: zekker6@gmail.com
    url: "https://github.com/zekker6/"
name: language-tool
sources:
  - https://github.com/language-tool/language-tool-docker
version: 1.0.2
