#
# IMPORTANT NOTE
#
# This chart inherits from k8s common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: noop
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # @default -- chart.appVersion
  tag: 0.0

# -- See the following files for additional environment variables:
# NEW_APP_REPLACE_ME
# @default -- See below
env: {}


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 100Mi
    emptyDir:
      enabled: false
