annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update ghcr.io/dgtlmoon/changedetection.io docker tag to v0.42
apiVersion: v2
appVersion: "v0.42"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.3
description: changedetection-io helm package
home: https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
icon:
keywords:
  - changedetection.io
  - urlmonitor
  - website-monitoring
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: changedetection-io
sources:
  - https://github.com/dgtlmoon/changedetection.io
  - https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
version: 1.12.0
