---
apiVersion: v2
appVersion: "0.40.0"
description: changedetection-io helm package
name: changedetection-io
version: 1.7.0
kubeVersion: ">=1.16.0-0"
keywords:
  - changedetection.io
  - urlmonitor
  - website-monitoring
home: https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
icon:
sources:
  - https://github.com/dgtlmoon/changedetection.io
  - https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
maintainers:
  - name: tuxpeople
    url: https://github.com/tuxpeople
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update image to 0.40.0
