name: "Charts: Release"

concurrency:
  group: gh-pages
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      charts:
        description: >
          Charts to release. Comma-separated string.
          Defaults to releasing everything.
        default: ""
        required: false

  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/**"

env:
  HELM_VERSION: 3.9.2

jobs:
  release-library-charts:
    name: Release Library charts to GitHub pages
    uses: ./.github/workflows/charts-release-ghpages.yaml
    with:
      charts_dir: "charts/library"
    secrets: inherit

  release-application-charts:
    name: Release Application charts to GitHub pages
    uses: ./.github/workflows/charts-release-ghpages.yaml
    needs:
      - release-library-charts
    with:
      charts_dir: "charts/apps"
    secrets: inherit
